services:
  # Node.js Backend
  backend:
    build:
      context: ./back
      target: dev
    container_name: trading_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # - BYBIT_TESTNET=false
      - ML_SERVICE_URL=http://ml-service:5000
      - ML_ENABLED=true
      - ML_AUTO_TRAIN=false
      - ML_TRAIN_DATA_LIMIT=1000
      - PRIMARY_STRATEGY=openai
      - ENABLE_STRATEGY_COMPARISON=true
    env_file:
      - ./back/.env
    volumes:
      - ./back/src:/app/src
      - ./back/package.json:/app/package.json
    restart: unless-stopped
    depends_on:
      - ml-service
      - mongo
      - redis
    networks:
      - trading_network

  # Python ML Service
  ml-service:
    build: ./ml-service
    container_name: trading_ml
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - MODELS_DIR=/app/artifacts
    volumes:
      - ./ml-service:/app
      - ml-models:/app/artifacts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - trading_network

  # React Frontend
  frontend:
    build:
      context: ./front
      target: dev
    container_name: trading_frontend
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_BACKEND_HOST=backend
    volumes:
      - ./front/src:/app/src
      - ./front/package.json:/app/package.json
      - ./front/vite.config.ts:/app/vite.config.ts
    command: npm run dev -- --host 0.0.0.0
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - trading_network

  # MongoDB for data storage
  mongo:
    image: mongo:6.0
    container_name: trading_mongo
    environment:
      MONGO_INITDB_DATABASE: trading_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - trading_network

  # Redis for caching
  redis:
    image: redis:6.2-alpine
    container_name: trading_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - trading_network

volumes:
  mongo_data:
  redis_data:
  ml-models:

networks:
  trading_network:
    driver: bridge 